#   &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Assignment

### Consider the below code to answer further questions:

In [4]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [5]:
array_list 

array(['1', '2', '3', '4', '5'], dtype='<U1')

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.
### Ans :-

### Python lists :<br>
### A list in Python is an inbuilt collection of items that can contain elements of multiple data types, which may be either numeric, character logical values, etc. It is an ordered collection supporting negative indexing. A list can be created using [] containing data values. Contents of lists can be easily merged and copied using Python’s inbuilt functions.<br>


### NumPy Arrays :
- ### Unlike lists, NumPy arrays are of fixed size, and changing the size of an array will lead to the creation of a new array  while the original array will be deleted.
- ### All the elements in an array are of the same type.
- ### Numpy arrays are faster, more efficient, and require less syntax than standard Python sequences.

### yes , there is a difference in the data types of variables list_ and array_list.

- ### The data type of list_ is a Python list (list).
- ### The data type of array_list is a NumPy array data type (<U1), indicating a Unicode string of length 1.
- ### As we can see in the output, the dtype of the given array object is '<U1' where 1 is the length of the longest string in the given array object.

In [24]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)


print("Array:", array_list)
print("Datatype:", array_list.dtype)

print("-" * 50) 

print("list:", list_)
print("Datatype:", type(list_))


Array: ['1' '2' '3' '4' '5']
Datatype: <U1
--------------------------------------------------
list: ['1', '2', '3', '4', '5']
Datatype: <class 'list'>


### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [33]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)


print("Data types in list_:")
for item in list_:
    print(type(item))


print("\nData types in array_list:")
for item in array_list:
    print(type(item))


Data types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:
### array_list = np.array(object = list_, dtype = int)
### Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both<br> the variables, list_ and array_list.

In [34]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_, dtype = int)


print("Data types in list_:")
for item in list_:
    print(type(item))


print("\nData types in array_list:")
for item in array_list:
    print(type(item))


Data types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


### Yes, there is a difference in the data types of the elements present in list_ and array_list.
- ### In list_ , all elements are of type str (string).

- ### In array_list, the elements have been explicitly converted to int using the dtype=int argument, so all elements are of type numpy.int32

### Consider the below code to answer further questions:

In [35]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

### Q4. Write a code to find the following characteristics of variable, num_array:
### (i) shape
### (ii) size
### Ans :-

In [36]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)


shape_of_array = num_array.shape


size_of_array = num_array.size

print("Shape of num_array:", shape_of_array)
print("Size of num_array:", size_of_array)


Shape of num_array: (2, 3)
Size of num_array: 6


### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
### [Hint: The size of the array will be 9 and the shape will be (3,3).]
### Ans :-

In [43]:
import numpy as np

data = np.zeros((3, 3))

print("3x3 Matrix with Zeros:")
print(data)


3x3 Matrix with Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Q6. Create an identity matrix of shape (5,5) using numpy functions?
### [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
### Ans :-

In [44]:
import numpy as np


data1 = np.eye(5)

print("5x5 Identity Matrix:")
print(data1)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
